name: CI/CD

on:
  workflow_dispatch:


jobs:
  golangci-lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Checkout 
        uses: actions/checkout@v2


      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.50
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.16


      - name: Go Test
        run: go run src/leetcode/Easy/0014_Longest_Common_Prefix/main.go
